### ISSUE TITLE
when will the LIFT package be released

### ISSUE THREAD

**Issue by amiltonwong** [cvlab-epfl/LIFT#1]
Hi, @etrulls ,

Glad to see your promising work. BTW, when do yo plan to release your LIFT package? Furthermore, which DL framework did you use to produce your Deep Network architecture? Caffe, Torch, Matconvnet, tensorflow, etc...?  Please also drop a message in Issues section for release notification when it is ready.

Thanks~

**Comment by kmyi** [comment]
Hi, it will be based on Theano and Lasagne. Instead of the issue tracker, you can put the repository on your watch list and you will be notified of the release :-)

Thanks,
Kwang

**Comment by amiltonwong** [comment]
Thanks @kmyid
