### ISSUE TITLE
Can you release your evaluation code?

### ISSUE THREAD

**Issue by 13331151** [cvlab-epfl/LIFT#10]
Hi,
  Jack again,
  Would you mind releasing the evaluation code for Repeatability, NN map, M. score, please? :) Thank you very very much!

**Comment by kmyi** [comment]
Hi Jack,

We will try to release it as soon as possible. In the meantime, you can have a look at the benchmark-orientation repo. It shares the same architecture.

Thanks,
Kwang

**Comment by 13331151** [comment]
Thank you, Kwang. You are very helpful! :)
