### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by njss** [cvlab-epfl/LIFT#12]
I am getting this error...after cmake ..
Can you help me?

CMake Warning at /home/nsilva/opencv-2.4.11/cmake/OpenCVConfig.cmake:161 (message):
  Found OpenCV Windows Pack but it has not binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)

CMake Error at CMakeLists.txt:11 (find_package):
  Found package configuration file:

    /home/nsilva/opencv-2.4.11/cmake/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

-- Configuring incomplete, errors occurred!
See also "/home/nsilva/Documents/python/theano/LIFT/c-code/build/CMakeFiles/CMakeOutput.log".

**Comment by kmyi** [comment]
That's quite weird. Also, the warning message seems to say that your OpenCV is for windows, whereas your path suggests you are not on windows.

Also, you probably want to install OpenCV 3 as that's the supported version.

I am closing the issue as it is an OpenCV installation issue.
