### ISSUE TITLE
Hard mining the Descriptor network

### ISSUE THREAD

**Issue by 13331151** [cvlab-epfl/LIFT#14]
I follow your advice of adding hard mining, and the performance of descriptor network work better than before but its still far worse compared to your released version. I wondering if there is anything I can pay attention to? Have you pre-trained the network before mining? And I extract patch with 6*sift_scale as radius for descriptor input, is it right? As for the mining rate, I double the mining rate every 5000 batches, so the mining rate become 1 at the 35000th iteration, is it the same as what you described in the paper?
I really appreciate your help because I have spent so much time in this part. Faint....

**Comment by kmyi** [comment]
Hi, regarding mining, we do something similar to yours. however, the mining rate goes as far as to having 5 forward passes and one backward pass. IIRC.

**Comment by 13331151** [comment]
>  the mining rate goes as far as to having 5 forward passes and one backward pass

Hi, thanks for the answer. So, do you mean that you select **128*5/mining_rate** hard samples out of **128*5** samples in 5 iterations? Thanks in advance.

**Comment by kmyi** [comment]
I think yes.
