### ISSUE TITLE
How to train the whole network with your provided Webcam and Oxford dataset?

### ISSUE THREAD

**Issue by Childhoo** [cvlab-epfl/LIFT#15]
The tested code provided trained descriptor/detector/orientation network. However, I hope to train those network with the provided dataset. Under python-code/Utils/networks there are files like "eccv_combined.py" "eccv_base.py" and "network_base.py", which are used to build the network architectures. 
I am wondering if this is the start point to train the whole network in your paper? 
**_Could you please give me some brief hints how to train the network with your provided Webcam and Oxford dataset?_** Thank you very much in advance.

**Comment by kmyi** [comment]
Hi, 

The training code is a mess at the moment. We will try to clean it up after the ICCV deadline and release it. In the meantime, you can look at some of the issues (maybe closed) related to implementing the training procedure if it helps.

Cheers,
kwang
