### ISSUE TITLE
‘img1_kp.txt’ with ‘img1_ori.txt’

### ISSUE THREAD

**Issue by YuYuYan** [cvlab-epfl/LIFT#17]
Hello， 
Bother you again. After I run your code,the results appear . but
I want to ask the difference between **‘img1_kp.txt**’ and‘**img1_ori.txt**’  in results.
why in ‘img1_kp.txt’  the **keypoints** is 1000, and in ‘img1_ori.txt’ the **keypoints** is 974.
what's the defference?
Thanks

**Comment by kmyi** [comment]
It could be that the descriptor/orientation support region is over the image boundary. In this case the keypoints are discarded.
