### ISSUE TITLE
This code includes learning procedure?

### ISSUE THREAD

**Issue by xuyan1115** [cvlab-epfl/LIFT#18]
Hi, 
I find that your release code is only for test (corresponding to Run-time pipeline sec. 3.6 in paper), but if I want to train whole network, do you provide codes about learning procedure?

Another problem is about patch. I saw your code in `compute_detector.py`, your input is a image, I can't find how did you construct the quadruplets patches.

Thanks.

**Comment by kmyi** [comment]
Unfortunately no. We plan to release that version soon.
