### ISSUE TITLE
13 degrees represent what in file img1_ori.txt 

### ISSUE THREAD

**Issue by YuYuYan** [cvlab-epfl/LIFT#19]
@cbecker @psycharo @maksay @pierrebaque @etrulls 
I know the first one and the second means kypoint x，y.   But  I want to konw the other degrees means?

Thanks

**Comment by YuYuYan** [comment]
@cbecker @psycharo @maksay @pierrebaque @etrulls

**Comment by kmyi** [comment]
Please do not randomly tag people. They are not maintainers of this repository. Also, you don't have to ping again. We will get back to you once we find the time.

**Comment by YuYuYan** [comment]
I'm so sorry that I am so anxious

**Comment by kmyi** [comment]
Hi, I just replied to your email. Will close the issue. You can look up kp_tools.py and there are detailed comments on this.
