### ISSUE TITLE
A problem happens when I start ./run.sh

### ISSUE THREAD

**Issue by kealennieh** [cvlab-epfl/LIFT#22]
when I start ./run.sh,  an valueError happens, which shows   
" Traceback (most recent call last):
  File "compute_detector.py", line 215, in <module> 
  image, verbose=False)
  ValueError : Invalid Value ("cpu") for configuration variable "gpu0" . Valid options start with one of "device", "opencl", "cuda" .
"

**Comment by hanghoo** [comment]
Maybe it reminds you that you have no GPU.

**Comment by kmyi** [comment]
Hi,

we cannot get that error on our side. probably your setup does not have a gpu?
