### ISSUE TITLE
Spatial Transformer

### ISSUE THREAD

**Issue by swarnakr** [cvlab-epfl/LIFT#24]
Hi,

Could you tell me how you use the spatial transformer function, ie which function is used to transform the input patch to the descriptor network according to the orientation?

**Comment by kmyi** [comment]
Hello,

This code does not have that part inside. The code for that and the training will be released (hopefully) soon. Drop an email address here, and I'll try not to forget to remind it to you when we get is ready.

Thanks!
Kwang

**Comment by Riverhe2014** [comment]
Hi,

**Comment by Riverhe2014** [comment]
Hi,
I am a researcher from Chinese Academy of Sciences China,I have used your train model to get descriptor,and can get the good match,However,When I use the other two picture which have strong rotation change,the match is not very well.I read your file named "README.md",in this file,you said "This model was trained with SfM data, which does not have strong rotation changes. Newer models work better in this case",I want to use your new models for scientific research.Would you send me a copy to my mailbox if it is convenient ?my email is  helijiang2013@163.com.
Thanks
LijiangHe

**Comment by yangninghua** [comment]
you will try not to forget to remind it to you when we get is ready.  
lgdyangninghua@163.com

**Comment by yangninghua** [comment]
Thanks!

**Comment by kmyi** [comment]
Hello, I completely forgot, but the tf-lift implementation should resolve this issue. Also, the more recent lf-net also has everything implemented in tensorflow, and you can also train your own if you want.
