### ISSUE TITLE
Match well with the train model which has big change

### ISSUE THREAD

**Issue by Riverhe2014** [cvlab-epfl/LIFT#25]
Hi,
         I am a researcher from Chinese Academy of Sciences China.
         Recently,I have read your paper named LIFT: Learned Invariant Feature Transform and dowloaded your code.
         It does me a lot of me.I have used your train model to get descriptor,and can get the good match,However,When I use the other two picture which have strong rotation change,the match is not very well.
          I read your file named "README.md",in this file,you said "This model was trained with SfM data, which does not have strong rotation changes. Newer models work better in this case",I want to use your new models for scientific research.Would you send me a copy to email helijiang2013@163.com if it is convenient,Thank you.

**Comment by Cospel** [comment]
I will be interested in this too.

**Comment by kmyi** [comment]
Hi Guys,

We are working on a model that could work on rotated images as well, and we will release one once we have are satisfied with it. That probably would be based on the new tf-lift repo though.

If you want, you can already train your own ones through that repo.

Cheers,
Kwang

**Comment by RuibinMa** [comment]
@Riverhe2014 Hi, can you tell me how you calculated the match? Thank you!
