### ISSUE TITLE
Is there a script to use these features extracted to match two images?

### ISSUE THREAD

**Issue by peterWon** [cvlab-epfl/LIFT#26]
Hi, thanks a lot for your great work!
As the above question title, I wonder if there is a  script or guide to use extracted features to match.Just like the video showed in this page[http://cvlab.epfl.ch/research/detect/lift](http://cvlab.epfl.ch/research/detect/lift).
I'll appreciate a lot if you can give me some help. Thank you!

**Comment by peterWon** [comment]
I found how to do this,it just lies in the three demo script,sorry to disturb.

**Comment by ghost** [comment]
Hi! could you tell me how did you do this? i can't find any example in the demo scripts given

**Comment by chuanzhidong** [comment]
> I found how to do this,it just lies in the three demo script,sorry to disturb.

@peterWon Could you please tell me the three demo script you used to match two images? Thanks a lot.
