### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yangninghua** [cvlab-epfl/LIFT#27]
#--------------------------------------------------------------------------------------
# Parameters for patch extraction

# automatically determined
f: patch.fMaxScale = np.max(self.model.fScaleList); # asserts make sure this is stored properly
f: patch.fRatioScale = (self.model.nPatchSizeKp / 2.0) / 2.0;	# to not resize when scale is 2
d: patch.nPatchSize = np.round(self.model.nDescInputSize * self.patch.fRatioScale / 6.0); # the large patch size for data. the desc will look at ratio scale of 6.0

#--------------------------------------------------------------------------------------
# Validation and test time parameters
d: validation.batch_size = 100;		# batch size of the implementation

# d: validation.nScaleInterval = 4;
  L-> skipped
# d: validation.nNMSInterval = 2;	  # number of intervals we look for
  L-> skipped
# 				  # NMS (3 would mean it goes up one
# 				  # octave in case of
# 				  # nScaleInterval=2)
#---------------------------------------------------------------------------------
 --------------------------------------------------- 
 Test Data Module 
 --------------------------------------------------- 
Traceback (most recent call last):
  File "compute_descriptor.py", line 111, in <module>
    test_data_in = data_module.data_obj(param, image_file_name, kp_file_name)
  File "/home/ynh/下载/LIFT/LIFT-master/python-code/Utils/dataset_tools/test.py", line 64, in __init__
    self.load_data(param, image_file_name, kp_file_name)
  File "/home/ynh/下载/LIFT/LIFT-master/python-code/Utils/dataset_tools/test.py", line 82, in load_data
    pathconf, param, image_file_name, kp_file_name)
  File "/home/ynh/下载/LIFT/LIFT-master/python-code/Utils/dataset_tools/test.py", line 129, in load_data_for_set
    kp = np.asarray(loadKpListFromTxt(kp_file_name))
  File "/home/ynh/下载/LIFT/LIFT-master/python-code/Utils/kp_tools.py", line 196, in loadKpListFromTxt
    kp_file = open(kp_file_name, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/ynh/下载/LIFT/LIFT-master/results/img1_ori.txt'

**Comment by kmyi** [comment]
Hello, as written in error report, you do not have img1_ori.txt prepared. Please check if you are following the instructions properly
