### ISSUE TITLE
ImportError: No module named flufl.lock

### ISSUE THREAD

**Issue by Miranda0920** [cvlab-epfl/LIFT#29]
when i run the file run.sh, error occurs as follow:
Traceback (most recent call last):
File “compute_detector.py”, line 43, in
from Utils.custom_types import paramGroup, paramStruct, pathConfig
File “/home/mitc/demo/LIFT-master/python-code/Utils/custom_types.py”, line 45, in
from flufl.lock import Lock
ImportError: No module named flufl.lock
Traceback (most recent call last):
File “compute_orientation.py”, line 40, in
from Utils.custom_types import paramGroup, paramStruct, pathConfig
File “/home/mitc/demo/LIFT-master/python-code/Utils/custom_types.py”, line 45, in
from flufl.lock import Lock
ImportError: No module named flufl.lock
Traceback (most recent call last):
File “compute_descriptor.py”, line 41, in
from Utils.custom_types import paramGroup, paramStruct, pathConfig
File “/home/mitc/demo/LIFT-master/python-code/Utils/custom_types.py”, line 45, in
from flufl.lock import Lock
ImportError: No module named flufl.lock

i have tried to install flufl.lock use "pip3 install flufl.lock",but it doesn't work. what should i do with this error?

**Comment by kmyi** [comment]
I believe the code is intended to run in Python2, and the shebang also specifies that.
For flufl.lock, they stopped supporting python2 in recent versions, so you'll have to install the latest Python2 version through specifying the version number in pip.
