### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by libaosir2** [cvlab-epfl/LIFT#32]
When I run the run.sh , error occurs as follow:
/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Parameters
#--------------------------------------------------------------------------------------
# Be careful as we do not use sophisticated parsing
# The parser will read until the semicolon
# 
# types are defined as below
# ss: multiple strings separated with commas
# s: string
# b: boolean
# f: float
# d: int
#--------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------
# Dataset parameters
ss: dataset.trainSetList = ECCV/piccadilly/; # All the first images of oxford dataset is used for training
s: dataset.dataType = ECCV;	  # the dataset type

#--------------------------------------------------------------------------------------
# Model parameters
s: model.modelType = Combined;	  # the network type
b: model.bNormalizeInput = 1;  	  # Normalize input to have zero mean and 1 std
f: model.fScaleList = np.array([1.0]); 	     # list of scale spaces (small means larger scale)

# GHH related
f: model.max_strength = -1;	# GHH softmax strength (-1 for hard)

# Keypoints
s: model.sDetector = tilde;	   # network architecture for kp
d: model.nFilterSize = 25;	  # Let's keep the number odd
d: model.nPatchSizeKp = 48;       # patch size for kp including moving
				  # regions we use something smaller
s: model.sKpNonlinearity = None; # use nonlinearity at end
f: model.fScaleList = np.array([1.0]); 	     # list of scale spaces (small means larger scale)
f: model.bias_rnd = 0.0;		# random noise added to bias
f: model.epsilon = 1e-8;		# epsilon for tilde

# Orientation
s: model.sOrientation = cvpr16;	   # network architecture for orientation

# Descriptor
s: model.sDescriptor = descriptor_imported;	   # network architecture for desc
d: model.nDescInputSize = 64;	  # Input size to be fed to the descriptor
# s: model.descriptor_export_folder = /cvlabdata1/home/trulls-data/kpdesc/torch/export/; 
  L-> skipped
s: model.descriptor_model = new-CNN3-picc-iter-56k.h5; # network configuration
s: model.descriptor_input = desc-input;	 # Descriptor input

#--------------------------------------------------------------------------------------
# Parameters for patch extraction

# automatically determined
f: patch.fMaxScale = np.max(self.model.fScaleList); # asserts make sure this is stored properly
f: patch.fRatioScale = (self.model.nPatchSizeKp / 2.0) / 2.0;	# to not resize when scale is 2
d: patch.nPatchSize = np.round(self.model.nDescInputSize * self.patch.fRatioScale / 6.0); # the large patch size for data. the desc will look at ratio scale of 6.0

#--------------------------------------------------------------------------------------
# Validation and test time parameters
d: validation.batch_size = 100;		# batch size of the implementation

# d: validation.nScaleInterval = 4;
  L-> skipped
# d: validation.nNMSInterval = 2;	  # number of intervals we look for
  L-> skipped
# 				  # NMS (3 would mean it goes up one
# 				  # octave in case of
# 				  # nScaleInterval=2)
#---------------------------------------------------------------------------------
Time taken to read and prepare the image is 20.172 ms
INFO: Testing double scale
resize to test is [1.95833333 1.70482819 1.48413914 1.29201816 1.12476714 0.97916667
 0.85241409 0.74206957 0.64600908 0.56238357 0.48958333 0.42620705
 0.37103478 0.32300454 0.28119178 0.24479167 0.21310352 0.18551739
 0.16150227 0.14059589 0.12239583]
scales to test is [ 1.          1.14869835  1.31950791  1.51571657  1.74110113  2.
  2.29739671  2.63901582  3.03143313  3.48220225  4.          4.59479342
  5.27803164  6.06286627  6.96440451  8.          9.18958684 10.55606329
 12.12573253 13.92880901 16.        ]
Time taken to resize image is 19.927ms
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/sandbox/cuda/__init__.py:556: UserWarning: Theano flag device=gpu* (old gpu back-end) only support floatX=float32. You have floatX=float64. Use the new gpu back-end with device=cuda* for that value of floatX.
  warnings.warn(msg)
Using gpu device 0: GeForce GTX 1060 3GB (CNMeM is disabled, cuDNN 5103)
1 #include <Python.h>
2 #include <iostream>
3 #include "theano_mod_helper.h"
4 #include "cuda_ndarray.cuh"
5 //////////////////////
6 ////  Support Code
7 //////////////////////
8 
9             static __global__ void kernel_reduce_ccontig_node_544270fe7a21a748315f83abfe0913cc_0(
10                     const unsigned int d0,
11                     const float *A,
12                     float * Z)
13             {
14                 const int threadCount = blockDim.x;
15                 const int threadNum = threadIdx.x;
16                 extern __shared__ float buf[];
17                 float myresult = 0;
18 
19                 if (warpSize != 32)
20                 {
21                     return;  //TODO: set error code
22                 }
23 
24                 for (int i0 = threadIdx.x; i0 < d0; i0 += blockDim.x)
25                 {
26                     myresult = myresult + A[i0];
27                 }
28                 
29         __syncthreads(); // some kernel do multiple reduction.
30         buf[threadNum] = myresult;
31         __syncthreads();
32 
33         // rest of function is handled by one warp
34         if (threadNum < warpSize)
35         {
36             //round up all the partial sums into the first `warpSize` elements
37             for (int i = threadNum + warpSize; i < threadCount; i += warpSize)
38             {
39                 myresult = myresult + buf[i];
40             }
41             buf[threadNum] = myresult;
42         /*Comment this optimization as it don't work on Fermi GPU.
43         TODO: find why it don't work or put the GPU compute capability into the version
44             // no sync because only one warp is running
45             if(threadCount >32)
46             {buf[threadNum] = buf[threadNum] + buf[threadNum+16];buf[threadNum] = buf[threadNum] + buf[threadNum+8];buf[threadNum] = buf[threadNum] + buf[threadNum+4];buf[threadNum] = buf[threadNum] + buf[threadNum+2];buf[threadNum] = buf[threadNum] + buf[threadNum+1];
.......

nvcc fatal   : Value 'sm_61' is not defined for option 'gpu-architecture'

['nvcc', '-shared', '-O3', '-arch=sm_61', '-m64', '-Xcompiler', '-fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/lbg/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.13-64/cuda_ndarray', '-I/home/lbg/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.13-64/cuda_ndarray', '-I/usr/local/cuda-7.5/include', '-I/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/numpy/core/include', '-I/home/lbg/devdata/anaconda2/envs/py2/include/python2.7', '-I/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof', '-I/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/sandbox/cuda', '-L/home/lbg/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.13-64/cuda_ndarray', '-L/home/lbg/devdata/anaconda2/envs/py2/lib', '-o', '/home/lbg/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.13-64/tmp7Txrh9/544270fe7a21a748315f83abfe0913cc.so', 'mod.cu', '-lcudart', '-lcublas', '-lcuda_ndarray', '-lpython2.7']
Traceback (most recent call last):
  File "compute_detector.py", line 215, in <module>
    image, verbose=False)
  File "/home/lbg/devdata/LIFT/python-code/Utils/solvers.py", line 148, in TestImage
    myNet = CreateNetwork4Image(pathconf, param, image, verbose=verbose)
  File "/home/lbg/devdata/LIFT/python-code/Utils/solvers.py", line 93, in CreateNetwork4Image
    ) + '_' + param.model.modelType.lower())
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/lbg/devdata/LIFT/python-code/Utils/networks/eccv_combined.py", line 45, in <module>
    import theano
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/__init__.py", line 116, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/sandbox/cuda/tests/test_driver.py", line 32, in test_nvidia_driver1
    profile=False)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/compile/function_module.py", line 1795, in orig_function
    defaults)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/compile/function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof/vm.py", line 1063, in make_all
    impl=impl))
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof/cmodule.py", line 1155, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof/cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/sandbox/cuda/nvcc_compiler.py", line 393, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', GpuCAReduce{add}{1}(<CudaNdarrayType(float32, vector)>), '\n', 'nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -arch=sm_61 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/lbg/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.13-64/cuda_ndarray -I/home/lbg/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.13-64/cuda_ndarray -I/usr/local/cuda-7.5/include -I/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/numpy/core/include -I/home/lbg/devdata/anaconda2/envs/py2/include/python2.7 -I/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/gof -I/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/Theano-0.9.0rc1-py2.7.egg/theano/sandbox/cuda -L/home/lbg/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.13-64/cuda_ndarray -L/home/lbg/devdata/anaconda2/envs/py2/lib -o /home/lbg/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.13-64/tmp7Txrh9/544270fe7a21a748315f83abfe0913cc.so mod.cu -lcudart -lcublas -lcuda_ndarray -lpython2.7', '[GpuCAReduce{add}{1}(<CudaNdarrayType(float32, vector)>)]')
/home/lbg/devdata/anaconda2/envs/py2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

 --------------------------------------------------- 
Traceback (most recent call last):
  File "compute_descriptor.py", line 111, in <module>
    test_data_in = data_module.data_obj(param, image_file_name, kp_file_name)
  File "/home/lbg/devdata/LIFT/python-code/Utils/dataset_tools/test.py", line 64, in __init__
    self.load_data(param, image_file_name, kp_file_name)
  File "/home/lbg/devdata/LIFT/python-code/Utils/dataset_tools/test.py", line 82, in load_data
    pathconf, param, image_file_name, kp_file_name)
  File "/home/lbg/devdata/LIFT/python-code/Utils/dataset_tools/test.py", line 136, in load_data_for_set
    angle = np.pi / 180.0 * kp[:, IDX_ANGLE]  # store angle in radians
IndexError: too many indices for array

I have no idea about it .what should i do with this error?

**Comment by kmyi** [comment]
Sorry, but 

> nvcc fatal : Value 'sm_61' is not defined for option 'gpu-architecture'

Is a related to Theano. Can't help you much with that one.
