### ISSUE TITLE
error: ‘CV_StsBadArg’ was not declared in this scope

### ISSUE THREAD

**Issue by tv12345** [cvlab-epfl/LIFT#34]
Hello,

I am attempting to install the library, however i keep running into this problem. I assumed, the problem is because of the updated opencv library, therefore i add some more directory into the sift.cpp file. The error disappears and the make is successful. But later i stumple upon [Errno 2] No such file or directory: '/home/hoo104/LIFT/results/img1_ori.txt' error.
I am using conda 2, python 2.7, opencv3.4, cuda 8.  Any suggestions to resolve this error.

Thank You

**Comment by kmyi** [comment]
Hi, you could potentially use the tf-lift version. The error message you get is probably not the first one. Looking at your environment, I think your theano environment might not be correct.

**Comment by Mohammed-Elias** [comment]
@tv12345 @kmyid  Could you please tell me how can I solve it ?

**Comment by kmyi** [comment]
Please do not necro a closed issue tracker. As answered previously, this is an environment setup issue that we cannot help.
