### ISSUE TITLE
The model with rotation augmentation

### ISSUE THREAD

**Issue by FWC13163296500** [cvlab-epfl/LIFT#36]
Hello, do you have the model with rotation augmentation, the .config file.
THX!

**Comment by kmyi** [comment]
For that, please use the tensorflow version, or even better, LF-Net.

**Comment by FWC13163296500** [comment]
Do I need to train a new model for rotation augmentation ？

**Comment by kmyi** [comment]
Please see the respective github repos. The readme already answers your question :-)

**Comment by FWC13163296500** [comment]
THX！
