### ISSUE TITLE
model and config files

### ISSUE THREAD

**Issue by mpkuse** [cvlab-epfl/LIFT#39]
Hi,
I figured out the correct versions of theano and flufl.lock. I think i got it running. 

In the folder python-code, I am trying to `compute_detector.py`. 
Traceback (most recent call last):
  File "compute_detector.py", line 61, in <module>
    raise RuntimeError('USAGE: python compute_detector.py '
RuntimeError: USAGE: python compute_detector.py <config_file> <image_file> <output_file> <bSavePng> <bUseTheano> <bPrintTime/optional> <model_dir/optional> <num_keypoint/optional> 

Where can I get the config_file and the model ?

**Comment by kmyi** [comment]
Please have a look at `run.sh`.

Thanks,
Kwang
