### ISSUE TITLE
Is Windows ok?

### ISSUE THREAD

**Issue by huangh12** [cvlab-epfl/LIFT#4]
Thanks for your codes!  I just wanna know can these codes run under window OS?  Thx

**Comment by gzhang8763** [comment]
The same question. I d like to ask also which OS you get the code running? I ran into some environment config problems, and am not sure if it is the OS problem.  Thanks! : )

**Comment by kmyi** [comment]
Hi guys,

The code is written in Python 2.7, so in theory it should be more-or-less platform independent.
We tested it on both Linux and OSX, but not sure about it on Windows.
