### ISSUE TITLE
Image Mactching

### ISSUE THREAD

**Issue by tsabtahi** [cvlab-epfl/LIFT#40]
Hi
Trying to do image matching as shown in the figure. 

Was able to generate the keypoints. each key point has a descriptor of size 128. However how to know the location of the keypoints (which is of size 12 ). Is there a script that I can follow.

**Comment by yike-chen** [comment]
I want to know too.

**Comment by ShilangChen1011** [comment]
I want to know too.

**Comment by kmyi** [comment]
See

https://github.com/cvlab-epfl/LIFT/blob/30414a61e97c33ae941b903a220952eecde1ba26/python-code/Utils/kp_tools.py#L40

Thanks.
Kwang
