### ISSUE TITLE
Requirements file is not specified enough

### ISSUE THREAD

**Issue by breakingflower** [cvlab-epfl/LIFT#41]
Tried to get the code to work but it seems the requirements are not backwards compatible. Can you specify package versions in the requirements file? 

I've tried the following: 
```
conda create -n lift anaconda 
pip install -r requirements 
cd c-code/build 
cmake ..
make 
cd .. 
cd .. 
./run.sh 
```
errors: first they were related to opencv, then flock, then hd5py, then .... 

Can you please provide a more specified list such as 
numpy=1.12 

Thanks

**Comment by breakingflower** [comment]
I have made a docker version of the [tf-lift](https://github.com/cvlab-epfl/tf-lift) implementation of the same authors, which you can use by pulling the image from 

```
docker pull fremmen/tf-lift
```

**Comment by kmyi** [comment]
Thanks. Unfortunately, as you probably noticed, this code base is very old and we also don't know which exact versions any more. Which is why we also implemented the tensorflow port. They perform a bit differently, but should be comparable. Thank you again for the docker port.
