### ISSUE TITLE
Some problems about patch size

### ISSUE THREAD

**Issue by zzxp** [cvlab-epfl/LIFT#46]
Hello！
I don't understand the patch size setting in your paper "LIFT: Learned Invariant Feature Transform".Why the 24σ ×24σ support region correspond to 128X128 ? And where the sift descriptor say it support region size is12σ ?
Looking forward to your reply！

**Comment by kmyi** [comment]
I am not sure I understand your question properly. For SIFT, you should look at the SIFT paper, or maybe even the SIFT implementation you are using. Descriptors are typically extracted by cropping out the proper support region, and then processing the cropped patch. This depends on the algorithmic design, and is typically parameterized by the sigma. Again, I would suggest studying the SIFT algorithm here.

**Comment by zzxp** [comment]
I have seen the SIFT paper,and descriptors computed from a 16x16 sample array，it does not related to 12σ？
![image](https://user-images.githubusercontent.com/26996462/74289701-b6fb0e00-4d6a-11ea-9cff-39b446ea3664.png)

**Comment by kmyi** [comment]
that 16x16 sample array is drawn on a 12sigma region on the local feature. E.g. 
https://www.vlfeat.org/overview/sift.html

**Comment by zzxp** [comment]
Sorry for disturbing you again.In SIFT,support region seems to be  3X1.5Xσ, where is the"**12**"?

**Comment by etrulls** [comment]
The size of the support region is 12 times the "scale" provided by OpenCV. It's a simple conversion factor.

**Comment by zzxp** [comment]
How is the correspondence between patch size and σ calculated in the paper? For example, 24σX24σ corresponds to 128X128, and 12σX12σ corresponds to 64x64.

**Comment by etrulls** [comment]
I am not sure what you're asking. The patch is 12σ where σ is the scale reported by OpenCV. For training, we extract a larger patch (24σ) from which we detect a keypoint and then crop a smaller patch (again, 12σ) which is what we use to extract the descriptor.

That's off the top of my head because that was 5 years ago.

**Comment by zzxp** [comment]
I know what you mean. 
![image](https://user-images.githubusercontent.com/26996462/74314509-8047e680-4db0-11ea-9306-01dd336f47dd.png)
I just want to know how this standardization process is achieved.

**Comment by etrulls** [comment]
That's what I just explained in my previous message:

![6aZ0BS4i1Rr](https://user-images.githubusercontent.com/5287643/74314849-7f925e80-4d76-11ea-8e68-ba625a1548eb.png)

**Comment by zzxp** [comment]
Well, thank you
