### ISSUE TITLE
Some Problems on Building

### ISSUE THREAD

**Issue by Javion11** [cvlab-epfl/LIFT#48]
When I build LIFT code on MACOS, it always appear problem on the "cmake .. '' step.As follows, 
**CMake Warning (dev) in CMakeLists.txt:
  AUTOGEN: No valid Qt version found for target SIFT.  AUTOMOC disabled.
  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Core)

  to your CMakeLists.txt file.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   SIFT

This warning is for project developers.  Use -Wno-dev to suppress it.**
Thanks very much for noting this problem！

**Comment by kmyi** [comment]
Hi. This code base is ancient. You might want to checkout the tensorflow version, which is also ancient but slightly less so. Also, this seems to be just a warning no?
