### ISSUE TITLE
Running error in Linux - Help appreciated

### ISSUE THREAD

**Issue by gzhang8763** [cvlab-epfl/LIFT#5]
Hello! I ran into mainly 4 problems when try to run the code. But in order to get things more clearly, I screenshot all the commanding info. (linux 16)
1. In the 3rd picture, when I ./run.sh, libSIFT.so has a undefined symbol problem
2. In the 7th picture, still during the running, in the test data module part, it can't find the file img1_kp.txt in result filefolder
3. In the last picture, in the other test module part, it can't find img_ori.txt in result filefolder
4. Are these 2 files generated during compiling? Because there is no file in the reuslt filefolder. Is it to say my cmake.. make are failed to some extent? Because when I try cmake .. it gives me a warning and says OpenCV_DIR should be manually point to my build of opencv library, even if I write 'export OpenCV_DIR=<path_of_opencv/build>' in terminal. But actually I got configuration and gerneration done at last.
I would be quite appreciated if you could give me some hints to continue. I have struggled with it for some days.... THANKS!

1
![image](https://cloud.githubusercontent.com/assets/23368111/20467049/56233314-af7f-11e6-913e-5511eb0e44b3.png)
2. 
![image](https://cloud.githubusercontent.com/assets/23368111/20467053/600ba6a4-af7f-11e6-88b7-188a24c9fd12.png)
3.
![image](https://cloud.githubusercontent.com/assets/23368111/20467055/66e5347c-af7f-11e6-9a35-03d279c415ef.png)
4.
![image](https://cloud.githubusercontent.com/assets/23368111/20467056/6e2501ea-af7f-11e6-9ca2-fd0e1aef7961.png)
5. 
![image](https://cloud.githubusercontent.com/assets/23368111/20467058/7486f804-af7f-11e6-8d85-38b2729d15b5.png)
6. 
![image](https://cloud.githubusercontent.com/assets/23368111/20467064/7b71d26a-af7f-11e6-98ba-1e97980e7ecb.png)
7. 
![image](https://cloud.githubusercontent.com/assets/23368111/20467066/a57364b6-af7f-11e6-81b5-2b233bb1f4b0.png)
8. 
![image](https://cloud.githubusercontent.com/assets/23368111/20467072/ac8619ec-af7f-11e6-9db3-5dfc33202e4d.png)

9. 
![image](https://cloud.githubusercontent.com/assets/23368111/20467075/b3fdd4d0-af7f-11e6-864e-a7b621b02891.png)
10. 
![image](https://cloud.githubusercontent.com/assets/23368111/20467081/bb9c091e-af7f-11e6-9cb2-dc6d5ccdd7a6.png)
11. 
![image](https://cloud.githubusercontent.com/assets/23368111/20467087/c3b3838e-af7f-11e6-8e2a-7167791a5cec.png)

**Comment by kmyi** [comment]
Well, the screenshot shows that your OpenCV is for windows although you are on Linux. You should first get Opencv installed properly

**Comment by hichem-abdellali** [comment]
@kmyid could you please share the configuration of the machine and how did you installed OpenCV 3 I have the same problem as @navia1991 
Thanks

**Comment by hichem-abdellali** [comment]
@navia1991 did you solved the problem ?

**Comment by gzhang8763** [comment]
@djidan10  nope.. I am a bit confused cauz the tutorial I followed to install opencv is denoted be used in ubuntu...Maybe there was some configuration problem it didn't mention. Anyway I am planning to re-install opencv again and find another installation tutorial online.  T___T

**Comment by kmyi** [comment]
Hi guys,

I am on Ubuntu 16.04.1 with OpenCV 3.1. I'll try to setup a fresh VM to re-test what's going on next week, when I get back to my office. 

In the meantime, can you check if the following works?

1. `import cv2` in python
2. pkg-config

Also, FYI, here's an [official tutorial on installing OpenCV](http://docs.opencv.org/3.1.0/d7/d9f/tutorial_linux_install.html)

**Comment by gzhang8763** [comment]
@kmyid   Hello! I have tried import cv2, it works. But I am not sure the pkg-config....
![image](https://cloud.githubusercontent.com/assets/23368111/20634959/e93a9130-b356-11e6-9c72-b11c4f3204a7.png)
![image](https://cloud.githubusercontent.com/assets/23368111/20634985/450e51c2-b357-11e6-97f3-6e63192da866.png)

Besides, did you make some typical configuration when install cmake? If i don't copy the code files into opencv/build, and fix opencv-3.1.0/cmake/OpenCVConfig.cmake  and change OpenCV_FOUND from FALSE to TRUE, then another error come out, sth like following:

Could not find module FindOpenCV.cmake or a configuration file for package OpenCV.
  Adjust CMAKE_MODULE_PATH to find FindOpenCV.cmake or set OpenCV_DIR to the
  directory containing a CMake configuration file for OpenCV.  The file will
  have one of the following names:
    OpenCVConfig.cmake
    opencv-config.cmake


Many thanks!!

**Comment by kmyi** [comment]
This is quite weird, as it seems that you have all the components installed, except something is wrong with the opencv installation. 

> If i don't copy the code files into opencv/build, and fix opencv-3.1.0/cmake/OpenCVConfig.cmake and change OpenCV_FOUND from FALSE to TRUE,

This is something you should not manually change. It should be able to discover OpenCV by itself. I think you are not following the OpenCV instructions properly.

**Comment by hichem-abdellali** [comment]
Hi @navia1991 
For me it is working now, I have reinstalled Ubuntu 16.04 then 
1 - install Python 3 directly on the machine (without using virtualenv )
2 - install Cuda 8.0 
3 - install OpenCV 3.1.0 

Now everything is working, so I advise you to remove old installation of OpenCV and Python and start from the beginning 

Try in this way, and I will help you if you encounter errors 
Good luck !

**Comment by hichem-abdellali** [comment]
Hi @kmyid 
Could you please see your email 
Thanks !

**Comment by gzhang8763** [comment]
@djidan10   I re-install ubuntu16 in a new virtual machine. Opencv works well this time. Only problem is CUDA. I got following error about GPU. I need to install cuda to run the code anyway. But when I check the tutorial, the first step is Verify You Have a CUDA-Capable GPU. It seems that CUDA only support NVIDIA, right? My graphic in intel HD... So anyway it is not possible to run the code in the current computer?
Thanks!
![1](https://cloud.githubusercontent.com/assets/23368111/20644694/166346ce-b43e-11e6-9a27-edc279632847.png)
![2](https://cloud.githubusercontent.com/assets/23368111/20644700/49c298ee-b43e-11e6-958e-f5ef773c9e7a.png)

**Comment by gzhang8763** [comment]
@kmyid 
Thanks! The official tutorial installation of OpenCV works quite well! :D

**Comment by kmyi** [comment]
Closing as it seems resolved :-)

**Comment by aigc-boys** [comment]
@navia1991  @djidan10  @kmyid 
I meet the same problem,could you help me?
I run it in the Ubutun 14.0.4, this program must be run in the Ubuntu 16.04?
I configure the opencv3.1.0 and python3.4 for severals times,i think my configure is ture,but it also have this error.
 This is the result of the cmake ..
![cmake](https://cloud.githubusercontent.com/assets/24646917/21306728/6cf35688-c60d-11e6-8881-5fb4cc07866d.png)

This is the result of the make
![make](https://cloud.githubusercontent.com/assets/24646917/21306773/a26ce2b6-c60d-11e6-8110-89e6c6a46fc9.png)

This is the error about GPU,but i install the cuda-8.0 in the Ubutun 14.0.4,it also arise a error.
![run2-gpu](https://cloud.githubusercontent.com/assets/24646917/21306831/e95605d6-c60d-11e6-91cc-c9839ef13e8b.png)

This is the error about img1_kp.txt, it can't look for this file.


This is the error about img1_ori.txt, it can't look for this file.

**Comment by kmyi** [comment]
@18191171661 The OpenCV part is definitely something not working on your side. I cannot help you much with that since it's an installation issue.

For the second problem, you also need cudnn. see the webpage in the error message for more details.

Cheers,
Kwang

**Comment by gzhang8763** [comment]
@18191171661  
Sorry to look at those problems happen to you as well.
For me, opencv should be well installed according to the link @kmyid  gives, if it is a brand new Ubuntu, which means no other interupt.
Try to re-install ubuntu if possible; or i recommend anaconda, opencv is far more easier to install there, and so are those python packages, just looking for opencv3 anaconda cloud.
For Cuda stuff, i am afraid i can't give you any hints because I found a computer already with Cuda installed.... but i recommend you follow the official tutorial in Nvidia webpage

Everything will be fine. : )

**Comment by aigc-boys** [comment]
@navia1991 
@kmyid 
Thank you very much, i will try it.

**Comment by aigc-boys** [comment]
@navia1991
@kmyid
Thanks for your reply!
I would like to test the performance of the LIFT algorithm and I have configured opencv for a long time.I will reconfigure it as your suggestion.
Could I ask you some quention?

Question1: Could you tell me the result of the LIFT algorithm? Could you cut a picture related to the final result? I want to the performance of this algorithm.
Question2: I would like to know that the "img1_ori.txt" file generator by run the code or get from the author?

I hope to receive you reply as soon as possible.

Thank you again!
Email: 1575262785@qq.com

**Comment by kmyi** [comment]
> Question1: Could you tell me the result of the LIFT algorithm? Could you cut a picture related to the final result? I want to the performance of this algorithm.

The current code does not really perform matching. I will try to come up with a minimal example, once I get the time.

> Question2: I would like to know that the "img1_ori.txt" file generator by run the code or get from the author?

It should be the output from the orientation estimator. 

Cheers,
Kwang

**Comment by gzhang8763** [comment]
@kmyid     I have sent you an email yesterday with some basic maybe a bit stupid questions. Could you have a look and give me some hints also? Thanks!  : )

**Comment by kmyi** [comment]
@navia1991 I got your e-mail. I am quite overwhelmed with work at the moment. I will get back to you.

And please do not necro this thread as it is closed :-)
