### ISSUE TITLE
What if I set   _LIFT_USE_THEANO=0 ??

### ISSUE THREAD

**Issue by huangh12** [cvlab-epfl/LIFT#8]
I got a question.  Since my GPU doesn't support cuDNN.  I edited the **run.sh** file and set the _LIFT_USE_THEANO=0 .  As a result, the code seems to run well without any error, except some warning.   And I got a result image named **img1_kp.txt.jpg** in the result directory.   Any thing wrong with me ?? thank you!

**Comment by ozgurovic** [comment]
For me it doesn't work. I get the following error:

Time taken using opencv for image size (2350, 3760) is 3541.709 milliseconds
Traceback (most recent call last):
  File "compute_detector.py", line 245, in <module>
    constant_values=-np.inf)]
  File "/usr/lib/python2.7/dist-packages/numpy/lib/arraypad.py", line 1320, in pad
    kwargs[i] = _normalize_shape(narray, kwargs[i])
  File "/usr/lib/python2.7/dist-packages/numpy/lib/arraypad.py", line 1044, in _normalize_shape
    raise ValueError(fmt % (shape,))
ValueError: Unable to create correctly shaped tuple from -inf

For the maintainers: Can you write the python version and known hardware configuration that the code works on?
Thanks for the code. I hope I can find the correct configuration to run it.

**Comment by kmyi** [comment]
Hi, we are using Python 2.7. the LIFT_USE_THEANO flag is for the keypoint part only. The  other parts still require you to have a GPU.
